name = "skeleton"
license = "MIT"
licenselink = "https://github.com/channprj/hugo-skeleton/blob/master/LICENSE"
description = ""
homepage = "https://github.com/channprj/hugo-skeleton"
tags = [
    "",
]
features = [
    "",
]
min_version = "0.30.2"

[author]
  name = "CHANN"
  homepage = "https://chann.kr"
